### ISSUE TITLE
process_windows.go 1 variable returns 2 values

### ISSUE THREAD

**Issue by sebastien6** [elastic/go-sysinfo#66] opened 2019-10-17 16:37 UTC
.got this error message:

.\..\..\github.com\elastic\go-sysinfo@v1.0.1\providers\windows\process_windows.go:283:6: assignment mismatch: 1 variable but tokenUser.User.Sid.String returns 2 values
..\..\..\github.com\elastic\go-sysinfo@v1.0.1\providers\windows\process_windows.go:292:7: assignment mismatch: 1 variable but tokenGroup.PrimaryGroup.String returns 2 values

sid, err:= tokenUser.User.Sid.String()
	if err != nil {
		return types.UserInfo{}, errors.Wrap(err, "failed to look up user SID")
	}
Sid.String seems to not return error, same for PrimaryGroup.String

**Comment by axw** [comment] 2019-10-18 01:45
Duplicate of https://github.com/elastic/go-sysinfo/issues/65 - fixed upstream in golang/x/sys already.

**Closed by axw** 2019-10-18 01:45 UTC
